export const SOUND_EVENT_DEFS = [
  { id: 'beam_shoot', label: 'BEAM - Charged Shot' },
  { id: 'beam_quick', label: 'BEAM - Quick Shot' },
  { id: 'grenade_shoot', label: 'Weapon - Grenade Shot' },
  { id: 'rocket_shoot', label: 'Weapon - Launcher Shot' },
  { id: 'sniper_shoot', label: 'Weapon - Sniper Shot' },
  { id: 'machinegun_shoot', label: 'Weapon - Machine Gun Shot' },
  { id: 'grenade_explode', label: 'Weapon - Grenade Explosion' },
  { id: 'rocket_explode', label: 'Weapon - Rocket Explosion' },
  { id: 'missile_lock', label: 'Weapon - Launcher Lock' },
  { id: 'missile_no_lock', label: 'Weapon - Launcher No Lock' },
  { id: 'launcher_charge_start', label: 'Weapon - Launcher Charge Loop' },
  { id: 'launcher_charge_store', label: 'Weapon - Launcher Chamber Stored' },
  { id: 'sniper_zoom_in', label: 'Weapon - Sniper Zoom In' },
  { id: 'sniper_zoom_out', label: 'Weapon - Sniper Zoom Out' },
  { id: 'weapon_empty', label: 'Weapon - Empty' },
  { id: 'weapon_switch', label: 'Weapon - Switch' },
  { id: 'ammo_pickup', label: 'Ammo Pickup' },
  { id: 'upgrade_roll', label: 'Upgrade - Roll Tick' },
  { id: 'upgrade_award', label: 'Upgrade - Award' },
  { id: 'enemy_melee', label: 'Enemy - Melee Hit' },
  { id: 'enemy_spawn', label: 'Enemy - Spawn' },
  { id: 'pause_open', label: 'Pause - Open' },
  { id: 'pause_close', label: 'Pause - Close' },
  { id: 'drop_ship_incoming', label: 'Drop Ship - Incoming' },
  { id: 'drop_ship_impact', label: 'Drop Ship - Impact' },
  { id: 'drop_ship_hatch_open', label: 'Drop Ship - Hatch Open' },
  { id: 'drop_ship_deploy_enemy', label: 'Drop Ship - Deploy Enemy' },
  { id: 'drop_ship_core_launch', label: 'Drop Ship - Core Launch' },
  { id: 'airstrike_targeting', label: 'Airstrike - Targeting' },
  { id: 'airstrike_confirm', label: 'Airstrike - Confirm' },
  { id: 'airstrike_incoming', label: 'Airstrike - Incoming' },
  { id: 'airstrike_whistle', label: 'Airstrike - Whistle' },
  { id: 'flight_start', label: 'Flight - Start' },
  { id: 'flight_boost_release', label: 'Flight - Boost Release' },
  { id: 'rocket_mode_toggle', label: 'Rocket - Mode Toggle' },
  { id: 'rocket_salvo_safe', label: 'Rocket - Salvo Safe' },
  { id: 'rocket_salvo_fire', label: 'Rocket - Salvo Fire' },
  { id: 'missile_scan_start', label: 'Missile - Scan Start' },
  { id: 'missile_scan_mode', label: 'Missile - Scan Mode' },
  { id: 'upgrade_choice_open', label: 'Upgrade Choice - Open' },
  { id: 'upgrade_choice_close', label: 'Upgrade Choice - Close' },
  { id: 'level_complete', label: 'Level Complete' },
  { id: 'map_menu_open', label: 'Map Menu - Open' },
  { id: 'map_menu_close', label: 'Map Menu - Close' },
  { id: 'map_select', label: 'Map - Select' },
  { id: 'map_size_select', label: 'Map - Size Select' },
  { id: 'difficulty_select', label: 'Difficulty - Select' },
  { id: 'pickup_full', label: 'Pickup - Already Full' },
  { id: 'ammo_low', label: 'Ammo - Low Warning' },
  { id: 'enemy_behind_warning', label: 'Enemy - Behind Warning' },
  { id: 'music_menu', label: 'Music - Menu' },
  { id: 'music_game', label: 'Music - In Game' },
  { id: 'charge_start', label: 'BEAM - Charge Loop' },
  { id: 'charge_full', label: 'BEAM - Full Charge Ding' },
  { id: 'enemy_hit', label: 'Enemy - Hit' },
  { id: 'enemy_kill', label: 'Enemy - Kill' },
  { id: 'air_support_kill', label: 'Air Support - Enemy Destroyed' },
  { id: 'gunship_cannon', label: 'Gunship - Cannon Shot' },
  { id: 'gunship_heavy_fire', label: 'Gunship - Heavy Cannon Fire' },
  { id: 'gunship_heavy_impact', label: 'Gunship - Heavy Impact' },
  { id: 'enemy_shoot', label: 'Enemy - Shoot' },
  { id: 'enemy_shoot_flanker', label: 'Enemy - Flanker Shot' },
  { id: 'enemy_shoot_shooter', label: 'Enemy - Shooter Shot' },
  { id: 'enemy_shoot_tank', label: 'Enemy - Tank Shot' },
  { id: 'enemy_shoot_drone', label: 'Enemy - Assault Drone Shot' },
  { id: 'enemy_missile_launch', label: 'Enemy - Missile Launch' },
  { id: 'enemy_missile_explode', label: 'Enemy - Missile Explosion' },
  { id: 'enemy_grenade_launch', label: 'Enemy - Grenadier Launch' },
  { id: 'enemy_grenade_explode', label: 'Enemy - Grenadier Explosion' },
  { id: 'enemy_muzzle_smoke', label: 'Enemy - Muzzle Smoke Puff' },
  { id: 'enemy_damage_smoke', label: 'Enemy - Damage Smoke' },
  { id: 'enemy_death_explode', label: 'Enemy - Death Explosion' },
  { id: 'enemy_death_explode_large', label: 'Enemy - Large Death Explosion' },
  { id: 'enemy_spotted', label: 'Enemy - Spotted Player' },
  { id: 'enemy_diver_dive', label: 'Enemy - Diver Dive' },
  { id: 'enemy_diver_explode', label: 'Enemy - Diver Explosion' },
  { id: 'headshot', label: 'Headshot' },
  { id: 'multi_kill', label: 'Multi-Kill Streak' },
  { id: 'player_damage', label: 'Player - Take Damage' },
  { id: 'player_low_health', label: 'Player - Low Health Warning' },
  { id: 'pickup', label: 'Pickup Collected' },
  { id: 'upgrade', label: 'Upgrade Selected' },
  { id: 'jump', label: 'Jump' },
  { id: 'footstep', label: 'Footstep' },
  { id: 'landing', label: 'Landing' },
  { id: 'level_start', label: 'Level Start' },
  { id: 'game_over', label: 'Game Over' },

  // -- VR Environment ----------------------------------------------------------
  { id: 'vr_model_spawn',      label: 'VR - Model Spawn' },
  { id: 'vr_model_delete',     label: 'VR - Model Delete' },
  { id: 'vr_model_grab',       label: 'VR - Model Grab' },
  { id: 'vr_model_release',    label: 'VR - Model Release' },
  { id: 'vr_model_snap',       label: 'VR - Model Snap to Ground' },
  { id: 'vr_light_spawn',      label: 'VR - Light Spawn' },
  { id: 'vr_light_toggle',     label: 'VR - Light Toggle' },
  { id: 'vr_ui_click',         label: 'VR - UI Orb Click' },
  { id: 'vr_transform_start',  label: 'VR - Transform Start' },
  { id: 'vr_transform_done',   label: 'VR - Transform Done' },
  { id: 'vr_transform_fail',   label: 'VR - Transform Fail' },
  { id: 'vr_chat_send',        label: 'VR - Chat Send' },
  { id: 'vr_chat_receive',     label: 'VR - Chat Receive' },
  { id: 'vr_drive_on',         label: 'VR - Drive Mode On' },
  { id: 'vr_drive_off',        label: 'VR - Drive Mode Off' },
];

export const SOUND_EVENTS = SOUND_EVENT_DEFS.map(event => event.id);
export const soundEventIds = new Set(SOUND_EVENTS);

export function soundEventById(id) {
  return SOUND_EVENT_DEFS.find(event => event.id === id) || null;
}
