# Task 21 becomes a decision again, now with its contract and design written.
import json
p = 'docs/render-tasks.json'; d = json.load(open(p, encoding='utf-8')); by = {t['id']: t for t in d['tasks']}
t = by['t21-static-refresh-skip']
t['title'] = 'Decide: give the forest materials their own refresh policy (no change to Three)'
t['criteria'] = ('Say yes, no, or ask. Yes means: forest-gpu.js subclasses the standard node material and overrides the one method Three calls to decide whether an object needs its per-frame refresh. Policy: a mesh never seen refreshes fully; the first mesh of each material each render refreshes (that writes the shared camera and light data); every other forest mesh refreshes only when forest-gpu has marked it changed. Off by default behind a flag with a URL override (?foreststatic=1 to try it, later the default if it holds). '
  'Two Node tests: the refresh decision table, and a guard that the object-side uniform set of each of the nine forest materials is exactly what the design lists, so a future per-frame uniform cannot silently break it. Then your walk with the trace on: the trace’s refreshed-over-checked count for the main scene is the direct measurement (204 of 204 today).')
t['why'] = ('The contract Astra asked for is written (scratchpads/fps-churn/static-skip/, three reports from the generated shaders and the served Three’s source). What a forest mesh privately owns: its slot offset, its world and normal matrices, the scale uniforms and a handful of material scalars, its own geometry and indirect buffer. What can change them, and who catches it: material and texture changes and the double-sided toggles bump the material version and Three rebuilds the render object; the render-origin rebase and every cull uniform ride the compute path, which is not gated; the rung gate, mirror pass and fallback only touch visibility; a palette rebake makes new meshes. What Three would NOT catch and forest-gpu must mark itself: the tree-scale, leaf-scale and leaf-sway writes (guarded on value change), a variant install swapping a mesh’s geometry and flagging its indirect buffer, and arena uploads in the pulled modes. One standing rule follows: a forest material property is only ever written together with needsUpdate, true today, enforced by the test. '
  'Why no Three patch: the refresh policy is an ordinary overridable material method whose only consumer is the refresh check, so the change stays inside forest-gpu.js and every other material keeps Three’s behaviour. Not promised: any millisecond figure. The recordings put render submission at 53 per cent of trees-on wall time, bindings 10 and node updates 8; this removes most of the forest’s share of those two, and the trace count says how much.')
d['updatedAt'] = '2026-09-10T04:40:00.000Z'
json.dump(d, open(p, 'w', encoding='utf-8'), separators=(',', ':'), ensure_ascii=False)
p = 'docs/render-progress-log.json'; d = json.load(open(p, encoding='utf-8'))
d['entries'].append({'at': '2026-09-10T04:40Z', 'title': 'Static refresh skip: contract and design written; no Three patch needed',
  'body': 'Design agent (scratchpads/fps-churn/static-skip/01 what the gate skips, 02 forest object contract from generated bindings, 03 design; dump and probe scripts and nine vertex WGSL dumps beside them). Verdict: option B, corrected: NodeMaterial.setupObserver is an ordinary overridable method whose returned object is consulted only by needsRefresh, so forest-gpu.js subclasses MeshStandardNodeMaterial with a refresh policy of its own: first initialisation always refreshes; the first render object of a material each render refreshes (writes the shared render group); other forest meshes refresh when their per-render-object epoch differs from the mesh’s forestEpoch, which forest-gpu bumps at the events that Three would not catch: setTreeScale, setLeafScale, setLeafSway (guard on value change; sway is written every syncRenderState), installVariant’s geometry swap and indirect needsUpdate, and arena uploads in the pulled modes. Everything else is caught already: material and texture changes bump material.version and RenderObjects.get recreates; the rebase and cull uniforms ride the ungated compute path; visibility toggles are not refresh matters; a rebake makes new meshes. Standing rule: forest material properties are written only with needsUpdate (true today; enforced by test). Also refuted on the way: a claim that objectGroup.version never rises in r184 (probe shows it does, per object). Tests specified: the decision table and the object-group uniform set per role. Measurement: the trace’s refreshes over refreshChecks. Task 21 is a decision again, with the design behind it; Astra asked to review the three reports.', 'commits': []})
json.dump(d, open(p, 'w', encoding='utf-8'), indent=2, ensure_ascii=False); open(p, 'a', encoding='utf-8').write('\n')
json.load(open('docs/render-tasks.json', encoding='utf-8')); json.load(open('docs/render-progress-log.json', encoding='utf-8')); print('ok')
