# The 02:10 to 02:20Z captures read; what they answer and what they do not.
import json
p = 'docs/render-tasks.json'; d = json.load(open(p, encoding='utf-8')); by = {t['id']: t for t in d['tasks']}
t = by['t22-leaves']
t['notes'] = (t['notes'] + ' ' if t['notes'] else '') + '[user: several traces, heaps and logs in; the last ones are trees on; some logs labelled trees off are trees on]'
t['outcome'] = ('Read the eight ?gputime=1 captures (02:10 to 02:20Z) with the forest state taken from the capture itself, not the label. None carries the leafnormal=fragment form and none has the leaves or leaf-shadow toggle off, so the fragment fix and the shadow role are still unmeasured in frame time. What they do show, same session: trees off walking 18.5 ms p50 with a 10.3 ms render call; trees on walking 24.6 to 44.7 ms p50 with a 16.5 to 25.3 ms render call, worsening through the session as the resident trees grew from 1,140 to 1,636. Standing with trees 14.6 against 13.3. The lag you feel with trees is main-thread submission, not the GPU. '
  'The GPU timestamps themselves I no longer trust as whole-frame numbers: they read 0.2 to 0.4 ms while moving and 1.6 ms standing, and a moving frame cannot cost the GPU less than a standing one; the resolve path can hand back a stale value while a resolve is in flight, so those columns are set aside until fixed. The two trees-on heap profiles show the Three uniform-range allocation gone since the light sharing; what remains is ours (road queries per texel, the player capsule against the terrain BVH, the kill-plane density scan every frame, per-texel cover objects, the batch-visibility walk), and an agent is on a same-content allocation pass for those now. The three DevTools recordings (22:12, 22:16, 22:20) go to Astra for long-task reading with trees on.')
t['criteria'] = 'When you next have a minute, only two walks are still wanted: base-game.html?trace=1 with trees on (default), then base-game.html?trace=1&leafnormal=fragment. Same route. The trace stages are the trustworthy measurement here; the GPU columns are not, for now.'
d['updatedAt'] = '2026-09-10T00:20:00.000Z'
json.dump(d, open(p, 'w', encoding='utf-8'), separators=(',', ':'), ensure_ascii=False)

p = 'docs/render-progress-log.json'; d = json.load(open(p, encoding='utf-8'))
d['entries'].append({'at': '2026-09-10T00:20Z', 'title': 'Trees-on captures read: submission, not GPU; GPU timestamps set aside; allocation pass launched',
  'body': 'Eight ?gputime=1 captures 02:10 to 02:20Z, forest state read from each capture. No leafnormal=fragment run and no toggle-off run, so the fragment fix and the shadow role stay unmeasured in frame time. Same session: trees off walking 18.5 ms p50, render call 10.3; trees on 24.6 to 44.7 p50, render call 16.5 to 25.3, worsening as resident trees grew 1,140 to 1,636; standing 14.6 against 13.3. GPU timestamps read 0.2 to 0.4 ms moving against 1.6 standing, which is not physical for a whole frame; Three’s resolve returns the last value while a resolve is pending and the page records it, so those columns are set aside. Heap profiles with trees on (2.2 and 1.9 GB): the uniform-range allocation is gone since the light sharing; remaining weight is road queries per texel (9 to 10%, boxed doubles per segment), the capsule against the terrain BVH (14 to 18%, mostly library math), the kill-plane density scan every frame (4 to 5%), per-texel cover objects (7%), the batch-visibility walk (3 to 4%). An Opus agent is on a same-content allocation pass over the parts that are ours, with parity tests. Three DevTools recordings with trees on handed to Astra.', 'commits': []})
json.dump(d, open(p, 'w', encoding='utf-8'), indent=2, ensure_ascii=False); open(p, 'a', encoding='utf-8').write('\n')
json.load(open('docs/render-tasks.json', encoding='utf-8')); json.load(open(p, encoding='utf-8'))
print('ok')
